name: TUF repository timestamp update

on:
  schedule:
    - cron:  '30 18 * * *'
  workflow_dispatch:

jobs:
  tuf-timestamp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install dependencies
        run: |
          pip install securesystemslib[pynacl]
          pip install git+https://github.com/theupdateframework/tuf.git
          pip install click

      - name: Repo snapshot
        env:
          online_keys: ${{ secrets.online_keys }}
        run: |
          cd metadata
          ../tufctl/tufctl edit timestamp touch

          git config user.name tufctl-repo-tool
          git config user.email jkukkonen@vmware.com
          git add timestamp.json
          git commit -m "Snapshot & sign"
          git show
          git push
