name: TUF repository timestamp

on:
  schedule:
    - cron:  '30 6,18 * * *'
  workflow_dispatch:

jobs:
  tuf-timestamp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install git+https://github.com/vmware-labs/repository-editor-for-tuf.git

      - name: Timestamp
        working-directory: metadata
        env:
          TUF_REPO_PRIVATE_KEY_38600820f11a5f7d7ff42e6dfc9b03fd60272a3be6f895da2d882cea8bb1e20f: ${{ secrets.TUF_REPO_PRIVATE_KEY_38600820f11a5f7d7ff42e6dfc9b03fd60272a3be6f895da2d882cea8bb1e20f }}
        run: |
          # verify is currently not able to tell e.g. expiry from real invalid metadata
          # so we can't verify before trying to timestamp
          #tufrepo verify --root-hash 24d9b03f10ce0fe2e648833de26af60a4a8cd4e65bb396a8200a3194ae8ea76e
          tufrepo --keyring=env edit timestamp touch

      - name: Commit new timestamp
        working-directory: metadata
        run: |
          tufrepo verify --root-hash 24d9b03f10ce0fe2e648833de26af60a4a8cd4e65bb396a8200a3194ae8ea76e

          git config user.name tufrepo
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit -a -m "Repository timestamp"
          git show
          git push
